version: '3.8'

services:
 web:
  container_name: Server
  build: ./server
  ports: 
   - "5000:5000"
  volumes:
   - servervol:/serverdata
   - clientvol:/clientdata
    
volumes:
 servervol:
 clientvol: