# Use the official Python Alpine image as the base image
FROM nginx:latest

# Copy all code to the working directory
COPY ./index.html /usr/share/nginx/html/


# Expose the port that Flask will be running on
#EXPOSE 8000
 
